### ISSUE TITLE
I get 'undefined' properties when try using plugin

### ISSUE THREAD

**Issue by e-sarychev** [ktryniszewski-mdsol/codeceptjs-cucumber-json-reporter#8]
Hi!
I try to use your plugin but when start it i get:
```
Error processing suite.before event:
TypeError: Cannot read property 'description' of undefined
...
TypeError: Cannot read property 'elements' of null
...
Error processing test.failed event:
TypeError: Cannot read property 'result' of null
```

I don't use BDD 
I write simple test like first from [this page](https://codecept.io/puppeteer/)
How can i fix it problem?

Starting by
"test-start": "HEADLESS=true codeceptjs run --steps --plugins cucumberJsonReporter"

deps:
```
"codeceptjs": "^3.3.3",
"codeceptjs-assert": "0.0.5",
"codeceptjs-cucumber-json-reporter": "^1.0.8",
"faker": "^6.6.6",
"mochawesome": "^7.1.3",
"puppeteer": "^13.5.1"
```

**Comment by ktryniszewski-mdsol** [comment]
This plugin is specifically meant for BDD/cucumber because it tries to read gherkin feature files, so it will not work with Codeceptjs vanilla type tests
